### ISSUE TITLE
This is completely broken in current elm?

### ISSUE THREAD

**Issue by Gastove** [elm-lang/websocket#28]
Er sooooo.

Elm 0.19 is out. The elm guide is entirely examples from 0.19. But this package is both broken from the package manager (websocket 1.0.2 just wont install at all), and, even cooler, throws a pretty bracing error at the compiler level if you try to vendor it:

```
Creating `effect` modules is relatively experimental. There are a couple in @elm
repos right now, but we have decided to be very cautious in expanding its usage.

Get rid of all the effect stuff in WebSocket to proceed.

Note: You can learn the reasoning behind this design choice at
<https://elm-lang.org/0.19.0/effect-modules>
```

My favorite part about this error is that the link "explaining" it 404s. 

So uh. What... what now?

**Comment by evancz** [comment]
This package has not been updated for 0.19 yet. I have heard lots of folks saying they need more features from this package, so I'd rather take that into consideration in the update rather than just doing the same stuff. I recommend using ports or 0.18 if you absolutely need this right this second.

**Comment by evancz** [comment]
I wrote more about this [here](https://discourse.elm-lang.org/t/updating-packages/1771).

I understand that you are frustrated and want to vent that frustration with the "Er soooo" and "So uh..." As a human being, it is hard to smile through that sort of interaction every single time, but I hope the longer explanation linked is more helpful.

**Comment by petmac** [comment]
Thanks for the update, @evancz. It may not always seem like it, but your work is appreciated.

In my small project, I moved my WebSocket code to JS and used ports, and it was OK. It didn't take long and it worked fine.

Tangent:

I upgraded to Elm 0.19 because I was getting a type system error from the compiler with 0.18. The real bug was in my code for sure, but being new to Elm I couldn't figure out what it was. Then after upgrading, I found that I had to overhaul my project before I could find the bug.

I understand the need to make these breaking changes, but I think I would have appreciated another 0.18 bugfix release that I could have used as a stepping stone to keep me going until more packages were updated for 0.19.

**Comment by Gastove** [comment]
Hi @evancz. Thanks for the replies. First: apologies. I didn't mean my rhetorical approach to come the way it very apparently did. Honestly, I was just trying to express my bewilderment. I decided to try and learn Elm last week, and it was the wrong week to do so. 

That said: the 0.19 docs still direct here. The README doesn't say, "incompatible with 0.19." There's no compatibility indicator of any kind. Yes, there is now an "Upgrade to 0.19" issue -- thank you for that! -- but master itself uses 0.19. It seemed likely to me that this package just hadn't been re-published yet, and so I spent a pretty frustrating while trying to vendor it until I finally hit error messages that are both deeply opaque and, at least at the time, unexplained. 

This is all to say: I would have loved an obvious front-page-of-the-README way to know that this package is fully a no-go for now. 

Thanks for your hard work and time.
